---
# Install with:
#   ansible-galaxy install -r requirements.yml
#   ansible-galaxy collection install -r requirements.yml

roles:
  # CIS Benchmark hardening for Amazon Linux 2023 (community maintained)
  - name: ansible-lockdown.amzn2023_cis
    src: https://github.com/ansible-lockdown/AMAZON2023-CIS.git
    scm: git
    version: main

collections:
  - name: amazon.aws
    version: ">=7.5.0"
  - name: community.aws
    version: ">=7.0.0"
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
